CREATE DATABASE 14C;

USE 14C;

CREATE TABLE dates(
    ID INT NOT NULL AUTO_INCREMENT,
    LABNR VARCHAR(255) NOT NULL,
    C14AGE INT NOT NULL,
    C14STD INT NOT NULL,
    C13 FLOAT,
    MATERIAL VARCHAR(255),
    SPECIES VARCHAR(255),
    COUNTRY VARCHAR(255),
    SITE VARCHAR(255),
    PERIOD VARCHAR(255),
    CULTURE VARCHAR(255),
    Phase VARCHAR(255),
    LOCUS VARCHAR(1000),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    METHOD VARCHAR(255),
    CALAGE INT NOT NULL,
    CALSTD INT NOT NULL,
    REFERENCE VARCHAR(1000),
    NOTICE VARCHAR(1000),
    PRIMARY KEY (ID)
);

LOAD DATA INFILE '/home/clemens/Rstats/neolithicR/data/radiocarbon/Europe.csv' 
INTO TABLE dates
FIELDS TERMINATED BY '\t' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
CHARACTER SET UTF8;

select * from dates where SITE = 'Karanovo';



